name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Authenticate to GitLab registry
        run: |
         echo "//gitlab.gazin.com.br/api/v4/packages/npm/:_authToken=\${{ secrets.TESTE_TOKEN }}" >> .npmrc
         npm login --registry=https://gitlab.gazin.com.br/api/v4/packages/npm/ --scope=@labs --always-auth
         rm .npmrc


      - name: Build teste-payment
        run: |
          npm install
          npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TESTE_TOKEN }}
          publish_dir: ./build
